// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv5jf14fB1D-kT32ohDbF8sOPJTbEutGk',
    appId: '1:1048000775904:web:29a8bc9e7c63da03a67285',
    messagingSenderId: '1048000775904',
    projectId: 'laghari-family',
    authDomain: 'laghari-family.firebaseapp.com',
    storageBucket: 'laghari-family.firebasestorage.app',
    measurementId: 'G-G3L359BMSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrqMq29RHMbuWPcIopKZ9E7PUbxTd5NNI',
    appId: '1:1048000775904:android:fdc5474e7ed85638a67285',
    messagingSenderId: '1048000775904',
    projectId: 'laghari-family',
    storageBucket: 'laghari-family.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD03Sf3SgBKhQQwnjH1jUousnbMJ6H3KGk',
    appId: '1:1048000775904:ios:639de806d4efe923a67285',
    messagingSenderId: '1048000775904',
    projectId: 'laghari-family',
    storageBucket: 'laghari-family.firebasestorage.app',
    iosClientId: '1048000775904-4gqmjs0sg2gmpfv25pep41n5dhdnude6.apps.googleusercontent.com',
    iosBundleId: 'com.laghari.family.laghariFamily',
  );
}
