import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ur'),
  ];

  bool get isUrdu => locale.languageCode == 'ur';
  TextDirection get textDirection =>
      isUrdu ? TextDirection.rtl : TextDirection.ltr;

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'Laghari Family',
      'app_tagline': 'Genealogy & Ancestral Lineage',
      'family_tree': 'Family Tree',
      'search': 'Search',
      'notifications': 'Notifications',
      'profile': 'Profile',
      'settings': 'Settings',
      'admin_panel': 'Admin Panel',
      'admin_login': 'Admin Login',
      'login': 'Login',
      'signup': 'Sign Up',
      'logout': 'Sign Out',
      'email': 'Email Address',
      'password': 'Password',
      'ok': 'OK',
      'full_name': 'Full Name',
      'father_name': 'Father Name',
      'address': 'Address / City',
      'sign_in_with_google': 'Sign In with Google',
      'create_account': 'Create Account',
      'already_have_account': 'Already have an account? Log In',
      'dont_have_account': "Don't have an account? Sign Up",
      'generation': 'Generation',
      'alive': 'Alive',
      'deceased': 'Deceased',
      'unknown': 'Status Unknown',
      'male': 'Male',
      'female': 'Female',
      'father': 'Father',
      'children': 'Children',
      'no_children': 'No direct children recorded',
      'birth_date': 'Birth Date',
      'death_date': 'Death Date',
      'notes': 'Historical Notes',
      'confidence': 'Data Confidence',
      'section': 'Lineage Section',
      'view_family_tree': 'View in Family Tree',
      'suggest_edit': 'Suggest Edit',
      'add_child': 'Request Add Child',
      'add_picture': 'Add Picture',
      'pending_requests': 'Pending Requests',
      'user_management': 'User Management',
      'export_data': 'Export Family Tree',
      'import_data': 'Import Family Tree JSON',
      'export_json_desc': 'Export current Firestore family data into JSON backup.',
      'import_json_desc': 'Validate and merge external JSON into Firestore.',
      'language': 'Language',
      'english': 'English',
      'urdu': 'اردو (Urdu)',
      'approve': 'Approve',
      'reject': 'Reject',
      'reason': 'Reason for suggestion',
      'submit': 'Submit',
      'cancel': 'Cancel',
      'no_requests': 'No pending requests',
      'no_members_found': 'No family members found matching your search.',
      'search_placeholder': 'Search by English name, Urdu name, Father, or ID...',
      'name_en': 'English Name',
      'name_ur': 'Urdu Name',
      'select_father': 'Select Father',
      'complete_profile_title': 'Complete Your Profile',
      'complete_profile_desc': 'Please provide additional details to finish registration.',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'role': 'Role',
      'block_user': 'Block User',
      'unblock_user': 'Unblock User',
      'status': 'Status',
      'active': 'Active',
      'blocked': 'Blocked',
      'family_members': 'Family Members',
      'mobile_number': 'Mobile Number',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'reset_password': 'Reset Password',
      'email_otp_title': 'Email Verification',
      'email_otp_desc': 'We sent a 6-digit verification code to',
      'resend_otp': 'Resend Code',
      'resend_in': 'Resend in',
      'wrong_email_edit': 'Wrong email or details? Go back and edit',
      'verify_code': 'Verify & Continue',
      'invalid_otp': 'Invalid verification code. Please check and try again.',
      'no_internet': 'No Internet Connection',
      'no_internet_desc': 'Please check your internet connection and try again.',
      'connection_restored': 'Connection Restored',
      'fit_whole_tree': 'Fit Whole Tree',
      'all_generations': 'All Generations',
      'view_in_tree': 'View in Family Tree',
      'passwords_dont_match': 'Passwords do not match',
      'invalid_phone': 'Please enter a valid Pakistani mobile number (e.g. 300 1234567)',
      'tree': 'Tree',
      'members': 'Members',
      'blood_group': 'Blood Group',
      'gender': 'Gender',
      'profession': 'Profession',
      'phone_number': 'Phone Number',
      'other': 'Other',
      'prefer_not_to_say': 'Prefer not to say',
      'about': 'About',
      'about_app': 'About App',
      'check_updates': 'Check for Updates',
      'update_available': 'New Update Available',
      'update_now': 'Update Now',
      'skip': 'Skip',
      'submit_request': 'Submit Request',
      'edit_member': 'Edit Member',
      'request_add_child': 'Request Add Child',
      'request_pending': 'Request Pending',
      'select_admin': 'Select Admin',
      'select_admin_hint': 'Select an Admin to review your request',
      'review_request': 'Review Your Request',
      'edit_request': 'Edit Request',
      'old_value': 'Old:',
      'new_value': 'New:',
      'audit_log': 'History / Audit Log',
      'audit_log_desc': 'Monitor administrative actions, approvals, and genealogy modifications.',
      'send_notification': 'Send Notification to All',
      'send_notification_desc': 'Broadcast announcement to all registered users.',
      'notification_title': 'Notification Title',
      'notification_message': 'Notification Message',
      'delete_member': 'Delete Member',
      'delete_member_confirm': 'Are you sure you want to delete this member from the family tree? This action will be logged in history.',
      'direct_management': 'Direct Family Tree Management',
      'direct_management_desc': 'Directly add, edit, or remove members without approval requests.',
      'rejection_reason_optional': 'Rejection reason (optional)',
      'mark_all_read': 'Mark all as read',
      'no_notifications': 'No notifications yet',
      'requester': 'Requester',
      'sent_notifications_history': 'Sent Notifications History',
      'new_child_info': 'New Child Information',
      'see_family_tree': 'See Family Tree',
      'locate_in_full_tree': 'Locate in Full Tree',
      'official_website': 'Official Website',
      'privacy_policy': 'Privacy Policy',
      'change_password': 'Change Password',
      'delete_account': 'Delete Account',
      'no_children_added_yet': 'No children have been added for this member yet.',
    },
    'ur': {
      'app_name': 'لغاری فیملی',
      'app_tagline': 'شجرہ نسب اور آبائی ورثہ',
      'family_tree': 'خاندانی شجرہ',
      'search': 'تلاش',
      'notifications': 'اطلاعات',
      'profile': 'پروفائل',
      'settings': 'ترتیبات',
      'admin_panel': 'ایڈمن پینل',
      'admin_login': 'ایڈمن لاگ ان',
      'login': 'لاگ ان',
      'signup': 'اکاؤنٹ بنائیں',
      'logout': 'لاگ آؤٹ',
      'email': 'ای میل ایڈریس',
      'password': 'پاس ورڈ',
      'ok': 'ٹھیک ہے',
      'full_name': 'مکمل نام',
      'father_name': 'والد کا نام',
      'address': 'پتہ / شہر',
      'sign_in_with_google': 'گوگل کے ساتھ سائن ان',
      'create_account': 'نیا اکاؤنٹ بنائیں',
      'already_have_account': 'پہلے سے اکاؤنٹ ہے؟ لاگ ان کریں',
      'dont_have_account': 'اکاؤنٹ نہیں ہے؟ رجسٹر کریں',
      'generation': 'پشت',
      'alive': 'حیات',
      'deceased': 'مرحوم',
      'unknown': 'معلوم نہیں',
      'male': 'مرد',
      'female': 'خاتون',
      'father': 'والد',
      'children': 'اولاد',
      'no_children': 'کوئی براہ راست اولاد درج نہیں',
      'birth_date': 'تاریخ پیدائش',
      'death_date': 'تاریخ وفات',
      'notes': 'تاریخی نوٹس',
      'confidence': 'معلومات کی تصدیق',
      'section': 'شاخ / سلسلہ',
      'view_family_tree': 'خاندانی شجرہ دیکھیں',
      'suggest_edit': 'معلومات میں ترمیم کی تجویز',
      'add_child': 'اولاد شامل کریں',
      'add_picture': 'تصویر شامل کریں',
      'pending_requests': 'زیر التواء درخواستیں',
      'user_management': 'صارفین کی انتظامیہ',
      'export_data': 'شجرہ نسب ڈیٹا برآمد کریں',
      'import_data': 'شجرہ نسب JSON درآمد کریں',
      'export_json_desc': 'موجودہ ڈیٹا کو JSON بیک اپ فائل کے طور پر ڈاؤن لوڈ کریں۔',
      'import_json_desc': 'بیرونی JSON فائل کو ڈیٹا بیس میں ضم کریں۔',
      'language': 'زبان',
      'english': 'English',
      'urdu': 'اردو',
      'approve': 'منظور',
      'reject': 'مسترد',
      'reason': 'وجہ / تفصیل',
      'submit': 'جمع کرائیں',
      'cancel': 'منسوخ',
      'no_requests': 'کوئی زیر التواء درخواست موجود نہیں',
      'no_members_found': 'تلاش کے مطابق کوئی رکن نہیں ملا۔',
      'search_placeholder': 'اردو نام، انگریزی نام، والد، یا شناختی کوڈ سے تلاش کریں...',
      'name_en': 'انگریزی نام',
      'name_ur': 'اردو نام',
      'select_father': 'والد کا انتخاب کریں',
      'complete_profile_title': 'پروفائل مکمل کریں',
      'complete_profile_desc': 'رجسٹریشن مکمل کرنے کے لیے بقیہ تفصیلات درج فرمائیں۔',
      'save': 'محفوظ کریں',
      'delete': 'حذف کریں',
      'edit': 'ترمیم',
      'role': 'عہدہ / کردار',
      'block_user': 'صارف بلاک کریں',
      'unblock_user': 'صارف ان بلاک کریں',
      'status': 'حالت',
      'active': 'فعال',
      'blocked': 'بلاک شدہ',
      'family_members': 'خاندان کے ارکان',
      'mobile_number': 'موبائل نمبر',
      'confirm_password': 'پاس ورڈ کی تصدیق',
      'forgot_password': 'پاس ورڈ بھول گئے؟',
      'reset_password': 'پاس ورڈ ری سیٹ',
      'email_otp_title': 'ای میل تصدیق',
      'email_otp_desc': 'ہم نے تصدیقی کوڈ اس ای میل پر بھیجا ہے:',
      'resend_otp': 'کوڈ دوبارہ بھیجیں',
      'resend_in': 'دوبارہ بھیجیں',
      'wrong_email_edit': 'غلط ای میل یا معلومات؟ واپس جا کر ترمیم کریں',
      'verify_code': 'تصدیق کریں اور آگے بڑھیں',
      'invalid_otp': 'غلط تصدیقی کوڈ۔ براہ کرم دوبارہ کوشش کریں۔',
      'no_internet': 'انٹرنیٹ کنکشن موجود نہیں ہے',
      'no_internet_desc': 'براہ کرم اپنا انٹرنیٹ کنکشن چیک کریں۔',
      'connection_restored': 'انٹرنیٹ بحال ہو گیا',
      'fit_whole_tree': 'پورا شجرہ دیکھیں',
      'all_generations': 'تمام پشتیں',
      'view_in_tree': 'خاندانی شجرے میں دیکھیں',
      'passwords_dont_match': 'پاس ورڈز مماثل نہیں ہیں',
      'invalid_phone': 'درست پاکستانی موبائل نمبر درج کریں (مثلاً 300 1234567)',
      'tree': 'شجرہ',
      'members': 'ارکان',
      'blood_group': 'بلڈ گروپ',
      'gender': 'جنس',
      'profession': 'پیشہ / شعبہ',
      'phone_number': 'فون نمبر',
      'other': 'دیگر',
      'prefer_not_to_say': 'بتانا پسند نہیں',
      'about': 'ایپ کے بارے میں',
      'about_app': 'ایپ کے بارے میں',
      'check_updates': 'اپڈیٹ چیک کریں',
      'update_available': 'نئی اپڈیٹ دستیاب ہے',
      'update_now': 'ابھی اپڈیٹ کریں',
      'skip': 'چھوڑیں',
      'submit_request': 'درخواست جمع کرائیں',
      'edit_member': 'رکن میں ترمیم',
      'request_add_child': 'اولاد شامل کرنے کی درخواست',
      'request_pending': 'درخواست زیر التواء',
      'select_admin': 'ایڈمن کا انتخاب کریں',
      'select_admin_hint': 'درخواست کا جائزہ لینے کے لیے ایڈمن منتخب کریں',
      'review_request': 'اپنی درخواست کا جائزہ لیں',
      'edit_request': 'درخواست میں ترمیم',
      'old_value': 'پرانی معلومات:',
      'new_value': 'نئی معلومات:',
      'audit_log': 'تاریخچہ / آڈٹ لاگ',
      'audit_log_desc': 'ایڈمنز کے تمام اقدامات، منظوریوں اور تبدیلیوں کا مکمل ریکارڈ۔',
      'send_notification': 'تمام صارفین کو اطلاع بھیجیں',
      'send_notification_desc': 'تمام رجسٹرڈ صارفین کو عمومی اعلان بھیجیں۔',
      'notification_title': 'اعلان کا عنوان',
      'notification_message': 'اعلان کا پیغام',
      'delete_member': 'رکن کو حذف کریں',
      'delete_member_confirm': 'کیا آپ واقعی اس رکن کو شجرہ سے حذف کرنا چاہتے ہیں؟ اس عمل کا ریکارڈ آڈٹ لاگ میں محفوظ ہوگا۔',
      'direct_management': 'شجرہ نسب کا براہ راست انتظام',
      'direct_management_desc': 'بغیر منظوری ارکان کا براہ راست اندراج، ترمیم یا اخراج کریں۔',
      'rejection_reason_optional': 'مسترد کرنے کی وجہ (اختیاری)',
      'mark_all_read': 'تمام اطلاعات پڑھی ہوئی کریں',
      'no_notifications': 'کوئی نئی اطلاع موجود نہیں',
      'requester': 'درخواست گزار',
      'sent_notifications_history': 'بھیجے گئے اعلانات کی تاریخ',
      'new_child_info': 'نئے بچے کی معلومات',
      'see_family_tree': 'ذاتی شجرہ نسب دیکھیں',
      'locate_in_full_tree': 'مکمل شجرے میں تلاش کریں',
      'official_website': 'سرکاری ویب سائٹ',
      'privacy_policy': 'پرائیویسی پالیسی',
      'change_password': 'پاس ورڈ تبدیل کریں',
      'delete_account': 'اکاؤنٹ مستقل حذف کریں',
      'no_children_added_yet': 'اس رکن کے لیے ابھی کوئی اولاد شامل نہیں کی گئی ہے۔',
    },
  };

  String translate(String key) {
    final lang = _localizedValues.containsKey(locale.languageCode)
        ? locale.languageCode
        : 'en';
    return _localizedValues[lang]?[key] ??
        _localizedValues['en']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ur'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
